# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CatDog1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CatDog1

  target 'CatDog1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CatDog1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
